### ISSUE TITLE
not working on ubuntu16

### ISSUE THREAD

**Issue by crazy-canux** [ringtail/snout#10]
WARN Failed to read files, Because of read /proc/sys/fs/binfmt_misc/register: invalid argument
WARN Failed to read files, Because of open /proc/sys/net/ipv4/route/flush: permission denied
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/all/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/default/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/docker0/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/docker1/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/docker_gwbridge/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/enp3s0f0/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/enp4s0/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/enp5s0/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/lo/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/vboxnet0/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/veth049626c/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/veth1657467/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/veth2009782/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/veth2a9426f/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/veth302d118/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/veth349ef38/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/veth4551040/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/veth69cd651/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/veth722b7ba/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/veth7ae1067/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/veth9b1b9ec/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/veth9fa3c82/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/vetha2831fe/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/vethae75a1c/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/vethb1940b3/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/vethc62ef08/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/vethc7a420e/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/vethcdd2acf/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/virbr0/stable_secret: input/output error
WARN Failed to read files, Because of read /proc/sys/net/ipv6/conf/virbr0-nic/stable_secret: input/output error
WARN Failed to read files, Because of open /proc/sys/net/ipv6/route/flush: permission denied
WARN Failed to read files, Because of open /proc/sys/vm/compact_memory: permission denied
panic: sync: negative WaitGroup counter

goroutine 49 [running]:
sync.(*WaitGroup).Add(0xc4201020c0, 0xffffffffffffffff)
        /usr/local/go/src/sync/waitgroup.go:75 +0x134
sync.(*WaitGroup).Done(0xc4201020c0)
        /usr/local/go/src/sync/waitgroup.go:100 +0x34
github.com/ringtail/snout/collectors/cpu.GatherProcessSystemCallWithinTime.func1(0xc4201020c0, 0x5183, 0xc4201020a9, 0xc42016c0c0)
        /Users/ringtail/go/src/github.com/ringtail/snout/collectors/cpu/system_call.go:120 +0x24b
created by github.com/ringtail/snout/collectors/cpu.GatherProcessSystemCallWithinTime
        /Users/ringtail/go/src/github.com/ringtail/snout/collectors/cpu/system_call.go:97 +0xe1

**Comment by ringtail** [comment]
try with `sudo` again.

**Comment by crazy-canux** [comment]
already did.

sudo snout --debug

**Comment by ringtail** [comment]
ok, I‘ll check it on `ubuntu 16.04`
